### ISSUE TITLE
some working sample would be nice

### ISSUE THREAD

**Issue by misterraj7** [whyvra/Whyvra.Blazor.Forms#2]
Hi,
I understand a  lot has been done for dynamic form building, but would be nice if you could have a working sample, a walk through exercise.

**Comment by whyvra** [comment]
As described in the README, this library is the base package for creating dynamic form builders. It includes the base classes and interfaces like `FormBuilder<TModel>` and `WhyvraComponentBase<TModel>` for you to create your own dynamic form builder and components. There are examples in the README on how to implement your own form builder and your own components.

This package does not include any working form builder.

I've created a working implementation of a FormBuilder for the Bulma CSS framework, which is available here [Whyvra.Blazor.Forms.Bulma](https://github.com/whyvra/Whyvra.Blazor.Forms.Bulma). There, you will find examples on how to use the BulmaFormBuilder to dynamically generate a form for your model class and how to tie in the validation too.
